#!/bin/bash
ruleFiles=$1

if [[ ! -e /etc/fail2ban/filter.d/$ruleFiles.conf ]];then
	touch /etc/fail2ban/filter.d/$ruleFiles.conf
	echo "[Definition]" > /etc/fail2ban/filter.d/$ruleFiles.conf
	echo "failregex = <HOST> Type regex" > /etc/fail2ban/filter.d/$ruleFiles.conf
fi
nano /etc/fail2ban/filter.d/$ruleFiles.conf
